# Generated by Django 4.2.6 on 2023-10-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('recruit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='채용공고_id')),
                ('recruit_position', models.CharField(default='', max_length=100, verbose_name='채용포지션')),
                ('recruit_compensation', models.BigIntegerField(default=0, verbose_name='채용보상금')),
                ('recruit_con', models.CharField(default='', max_length=100, verbose_name='채용내용')),
                ('recruit_skills', models.CharField(default='', max_length=100, verbose_name='사용기술')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='회사_id')),
            ],
        ),
    ]
